version: '2'
services:
  web:
    ports:
      - 8000:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
    image: coderaiser/cloudcmd
    environment:
      - CLOUDCMD_PREFIX='/cloudcommand'
    container_name: cloudcommander
    networks:
      - proxy
networks:
  traefik_proxy:
    external:
      name: proxy
  default:
    driver: bridge